services:
  web:
    build: .
    container_name: online-shop-teclads
    ports:
      - "9000:9000"
    env_file: 
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - shop-network

  db:
    image: postgres:13
    container_name: database
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - teclads-data:/var/lib/postgresql/data
    networks:
      - shop-network


networks:
  shop-network:
    driver: bridge

volumes:
  teclads-data: