services:
  web:
    build: .
    container_name: online-shop-teclads
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - shop-network

  db:
    image: postgres:13
    container_name: database
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - teclads-data:/var/lib/postgresql/data
    networks:
      - shop-network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - shop-network
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery-worker
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    networks:
      - shop-network
    command: celery -A app.tasks.email.celery worker --loglevel=info

networks:
  shop-network:
    driver: bridge

volumes:
  teclads-data:
