"""Initial migration

Revision ID: 553b4033094c
Revises: 
Create Date: 2025-01-22 14:55:17.754654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553b4033094c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
