"""defualt value for total price

Revision ID: 925b901b3fa1
Revises: 553b4033094c
Create Date: 2025-01-22 15:03:19.320956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925b901b3fa1'
down_revision = '553b4033094c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
